dist: xenial

cache:
  directories:
    - $HOME/.cache/composer/files

language:
  - php

before_install:
  # Speed up build time by disabling Xdebug.
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  # https://twitter.com/kelunik/status/954242454676475904
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
  - composer require squizlabs/php_codesniffer:"$PHPCS_BRANCH" --update-no-dev --no-suggest --no-scripts
  - composer install --dev --no-suggest

script:
  # Run the unit tests.
  - ./bin/unit-tests

  # Run ruleset tests.
  - ./bin/ruleset-tests

# Rather than a `matrix` property, we use build stages. This allows early
# build failure for basic linting and sniffing issues.
# @link https://docs.travis-ci.com/user/build-stages/
#
# PHP >= 7.3 & PHPCS < 3.3.1 is known to fail.
# @link https://github.com/squizlabs/PHP_CodeSniffer/issues/2086.
#
# We can't use Matrix Expansion here, since we need to exclude jobs for the known failures,
# which Matrix Expansion does not yet support. We list each combination instead.
# @link https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-jobs

stages:
  - lint
  - sniff
  - test

jobs:
  allow_failures:
    - php: "7.4snapshot"
  fast_finish: true
  include:

    - stage: lint
      php: 7.2
      env: PHPCS_BRANCH="dev-master"
      before_install: phpenv config-rm xdebug.ini || echo 'No xdebug config.'
      install: false
      cache: false
      script:
        # Lint the PHP files against parse errors.
        - ./bin/php-lint

        # Add PHPCS locally for the XSD.
        - composer require squizlabs/php_codesniffer
        # Validate the XML files and check the code-style consistency of the XML files.
        - ./bin/xml-lint

        # Validate the composer.json file.
        # @link https://getcomposer.org/doc/03-cli.md#validate
        - composer validate --no-check-all --strict
      addons:
        apt:
          packages:
            - libxml2-utils

    - stage: sniff
      php: 7.2
      env: PHPCS_BRANCH="dev-master"
      before_install: phpenv config-rm xdebug.ini || echo 'No xdebug config.'
      install: composer install --dev --no-suggest
      script:
        # Run PHPCS against VIPCS.
        - ./bin/phpcs

    # PHPCS 3.2.3 is the lowest supported release
    - stage: test
      php: 5.6
      env: PHPCS_BRANCH="dev-master"

    - stage: test
      php: 5.6
      env: PHPCS_BRANCH="3.2.3"

    - stage: test
      php: 7.0
      env: PHPCS_BRANCH="dev-master"

    - stage: test
      php: 7.0
      env: PHPCS_BRANCH="3.2.3"

    - stage: test
      php: 7.1
      env: PHPCS_BRANCH="dev-master"

    - stage: test
      php: 7.1
      env: PHPCS_BRANCH="3.2.3"

    - stage: test
      php: 7.2
      env: PHPCS_BRANCH="dev-master"

    - stage: test
      php: 7.2
      env: PHPCS_BRANCH="3.2.3"

    # Only use PHPCS_BRANCH="dev-master" from this point, because PHPCS 3.3.1+ is needed to support PHP 7.3+
    - stage: test
      php: 7.3
      env: PHPCS_BRANCH="dev-master"

    - stage: test
      php: "7.4snapshot"
      env: PHPCS_BRANCH="dev-master"
